<Project Sdk="Microsoft.NET.Sdk.Web">

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi"/>
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Users\" />
        <Folder Include="Users\UseCases\" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\DandyMediator.Validation\DandyMediator.Validation.csproj" />
    </ItemGroup>

</Project>
