<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<EnablePackageValidation>true</EnablePackageValidation>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<PackageId>DandyMediator</PackageId>
		<Authors>Nicolai Wolf</Authors>
		<Description>Implementation for the mediator pattern.</Description>
		<RepositoryUrl>https://github.com/Nico1395/dandy-mediator</RepositoryUrl>
		<PackageTags>Mediator</PackageTags>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

</Project>
