namespace DandyMediator;

/// <summary>
/// Service sends <see cref="IRequest"/>/<see cref="IRequest{TResponse}"/> through the request pipeline.
/// </summary>
public interface IRequestSender
{
    /// <summary>
    /// Sends the given <paramref name="request"/> through the messaging pipeline.
    /// </summary>
    /// <typeparam name="TResponse">Type of response expected.</typeparam>
    /// <param name="request">Request being sent.</param>
    /// <param name="cancellationToken">Cancellation token for aborting asynchronous operations.</param>
    /// <returns>The response generated by the request handler or middleware.</returns>
    Task<TResponse> SendAsync<TResponse>(IRequest<TResponse> request, CancellationToken cancellationToken = default);

    /// <summary>
    /// Sends the given <paramref name="request"/> through the messaging pipeline.
    /// </summary>
    /// <param name="request">Request being sent.</param>
    /// <param name="cancellationToken">Cancellation token for aborting asynchronous operations.</param>
    Task SendAsync(IRequest request, CancellationToken cancellationToken = default);
}
